language: python
services:
  - docker
python:
  - "2.7"
sudo: required
install:
  - make deps
script:
  - make lint
  - make test_xunit
after_success:
  - make docker_build
deploy:
  provider: heroku
  app: quiet-atoll-68807
  api_key: ${HEROKU_API_KEY}
